env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - standard
  - plugin:prettier/recommended
plugins:
  - import-order-autofix
parserOptions:
  ecmaVersion: 2018
rules:
  prettier/prettier: error
  no-console: off
  import/order: error
  sort-keys: error
