env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - standard
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2018
rules:
  no-console: off
  sort-imports: error
  sort-keys: error
  import/order:
    - error
    - newlines-between: always
  prettier/prettier: error
