---
description: ある寒い日の夜、一人の青年が、自宅への帰路についていた。いつもどおりの道順。だがその途中、事故に出くわしてしまい…
tweetable: true
layout: novel.pug
---
= #01 背後から聞こえた舌なめずりの音

[#コンビニを出る青年]
（あ〜、もう…）

「…全然見つからないなぁ」

そうつぶやきながら、コンビニの自動扉から出てくる青年がいた。

｟これで何軒目のコンビニよ？｠

（たしか4軒目）

[#ひやしもちもち金玉が見つからない]
彼はスマホの画面を見ながら、苦い顔を浮かべている。

「どこに売ってるんだ…[.point]__ひやしもちもち金玉__…」

（[.point]__ひやしもちもち金玉__はどこだぁぁっ！！）

画面に表示されていたのは、コンビニスイーツの記事だった。

[#その言い方はマズイでしょ]
｟おいおい、俗称でぼやくなよ｠

（あれ、声に出しちゃってた？）

｟出てたぞ｠

｟やばい人じゃんwww｠

｟正式名称は「大きなタピオカみたいな大福」な｠

（うるせぇ）

彼はスマホの地図を確認すると、自転車に乗り、コンビニを背に走り出す。

[#脳内会話]
（重要なのは正式名称じゃあない！この俗称で！俺様は！食欲を刺激されたのだ！！だからこのままでいく）

｟にしたって、もう少し呼び方は考えようず。聞かれたらマズイ｠

｟ただでさえお前は、[.quot]__ruby:われわれ[頭の中の声]と会話してる__ようなイタイ奴なんだからな｠

[#草生し草太郎]
｟すれ違った人はこう思うだろう：キモッ｠

｟それで逮捕か。そんなん草しか生えないわwww｠

（やめろやめろ、頭の中で草を生やすな！）

彼は一人で走りながら、周囲をチラリと確認する。信号機と建物の明かりだけが浮かぶ肌寒い夜道。あたりに人の気配は無かった。

[#刑務所生活の実態]
（こんな時間だ。多少声に出てしまったって、誰も聞いちゃいないだろうよ）

｟はぁ〜、刑務所でタダ飯生活はまだ先かぁ〜www｠

｟不謹慎｠

（いいか草野郎、俺はタダ飯生活のために捕まったりはしない）

｟実際は労働があって大変。タダ飯ってわけにゃあいかんよ｠

[#脱線修正]
信号機が赤に点灯した交差点で、彼は自転車を停める。そして再びスマホを取り出した。

（はいはい、ruby:閑話休題[かんわきゅうだい]！そろそろ話を戻すぞ。えーっと、次のコンビニは…）

「げっ、遠い…」

｟けっこう距離があるなぁ｠

｟逆に考えよう。運動になるゾ｠

[#最近のニュース]
｟いや、ここまでくると時間のロスのほうがキツイ。それに…｠

彼は、画面の上をチラリと見た。ニュースアプリの通知のアイコン。最近よく聞く[.voice]__失踪事件__のニュース速報だった。

｟出発する時にも母親に言われたじゃん。最近物騒だから早く帰って来いって｠

（うむむ…）

[#ブームは過ぎた]
｟だいたい、なんでブームの時に買いに行かなかったんだ！もうどこも取り扱ってないって｠

｟コンビニは商品の入れ替わりが早い。もうどこにも売ってないぞ、たぶん｠

（仕方ないでしょ！togetterをさまよってたときに偶然見つけたんだ！）

[#寒さでやかましくなる頭の中]
｟もう諦めて帰ろうよ〜！寒いよ〜！｠

｟寒い〜！｠

｟氷漬けになるー！｠

｟ここはイイーキルスだった…？｠

（やかましいなぁ…）

彼は、首にかけていたイヤホンを耳に入れる。そして、スマホで音楽の再生を始めた。

[#頭は音楽で静けさを取り戻す]
（ふぅ…これで静かになるな）

「いや、曲がかかってるからそれは無いか」

曲を再生した途端、彼の脳内から他の声が消失する。音楽を聞くとき、頭の中の声は消える。いつものことだった。

[#この先のこと]
「さて、と」

（次はどうしようか…）

彼はスマホの画面を地図に戻し、この先の事を考える。目的のスイーツは手に入っていない。しかし気温は低く、風邪をひきそうなほどに寒い。スイーツは4軒のコンビニを回っても見つからない。もう売っていないと考えるのが妥当だった。

[#帰宅開始]
「…帰るか」

彼は、今まで走ってきた道を引き返し、自宅へ向けて走り出した。人通りの無い交差点。静かな夜の住宅街。今までの道を逆向きに走りながら、途中で寄ったコンビニの事を考える。

[#スイーツの味が気になる]
（はぁ〜食べたかったなぁ。ショタのふわふわ金玉みたいな食感の大福って、どんなのかめちゃくちゃ気になる）

坂道を登り、道を曲がる。家に着くまであと少し。

[#突然の出来事]
（ネットで販売とかしてないかな）

最後の交差点を通り過ぎたその時、spacing:5[]背後から、轟音が響いた。

「イイイッ！！？」

彼は慌ててブレーキをかけ、自転車を停車させる。そして、耳のイヤホンを抜きながら、音の方向を振り返った。

[#事故に遭遇]
「っ…事故…？」

後ろを向いた彼のruby:眼[まなこ]に、激突して変形した自動車が映った。フロントガラスは砕け散り、ヘッドランプから光が漏れている。

[#脳内会話復活]
｟うわーお、本物の事故だ…｠

｟あーあ、やっちまったね。イヤホンしながら走るから…｠

｟いや、それは無い。車との距離を考えると、交差点を通った時に来てはいなかったはず。我々が通過してから来た車だ｠

[#救助しなくては]
（重要なのはそこじゃないでしょ。えーっと…と、とにかく110番！）

｟落ち着いて！まず先に怪我人を助け出さないと。到着を待ってたら死ぬかも｠

「そうだ…まず確認、次に救助、それから110番！」

[#車内確認]
彼は自転車を近くの壁に立てかけると、小走りで自動車へ向かう。ヘッドライトの強い明かりで、暗い車内の様子は見えない。

「大丈夫ですか！怪我はしていませんか！」

彼は声を張り上げながら、車内を覗き込む。

「意識はありま──」

[#誰もいない車内]
車内をスマホのライトで照らす。だが、車内を見たとき、彼の言葉は止まってしまった。

（誰も…いない…？）

車内には、人の姿がなかった。衝突事故を起こしたのだから、さっきまで走っていたはず。なのに、誰も乗っていない。

[#誰もいないなんておかしいよね]
｟いや、おかしいよね…普通は誰かいるもんだよね？気絶した人とか、挟まれて出れない人とか｠

｟ぶつかる前に飛び降りたってこと？｠

「後ろの道で倒れてるのか…？」

｟と、とにかく、車内に人はいない。緊急の救出が必要な人は無し。110番！｠

[#背後から聞こえる何かの音]
スマホの画面を操作し、電話をかけようとする。するとその時、背後から奇妙な音が聞こえた。

「…？」

何かが聞こえた。しかし、なんの音なのかははっきりしない。

（何か聞こえた？）

音の原因を確認しようと、彼は後ろを振り返り、そして──spacing:5[]体を固めてしまった。

[#獲物の様子]
振り向いたとき、最初に視界に入ったのは足だった。だらりとぶら下がった人間の足。ズボンを履いていたせいで、一瞬それが足だとは認識できなかった。次に視界に入ったのは、その足の持ち主。ズボンを固定するベルトの明色が、暗色のズボンの中で浮いている。

[#捕食者の姿：首と腹側]
そして、その人間を咥えた、巨大なナニカの姿。[.voice]__獲物__を咥えた頭部が、長い首の上にある。その首は段々と太くなりながら、胴体へとつながっている。胴体の腹側は、胸に当たる上半分がピンク色の体毛に覆われ、下半分の腹は毛がなく真っ白な皮膚。anchor:捕食者の姿：腹部と四肢と翼[]丸く膨れた白い腹部は、生きていることを示すようにゆったりと動いている。胴体からはruby:前脚[まえあし]が伸び、地面をしっかりと踏みつけている。濃い赤桃色の甲殻で覆われた、筋肉質な前脚。そして、背中側には二対の翼。まるで、神話の世界のドラゴン。

[#獲物を咥え直す捕食者]
その生き物は、頭部を上へ勢いよく振り上げる。その瞬間、口を少しだけ開き、獲物を開放した。だが、咥えられた獲物は、振り上げられた勢いで空中に留まる。獲物が落下を始めるよりも早く、生き物は再び口を閉じ、獲物を咥え込んでしまった。anchor:呑み込まれる獲物[]さっきまで見えていた獲物の体は、今や生き物の口の中。生き物は上を向いたまま、喉を膨らませる。

ゴックン

その膨らみは、ゆっくりと首を下っていき、胴体の中へと消えてしまった。時間にして、わずか3秒。さっきまで咥えられていたはずの人間が、今は影も形もない。

[#捕食者に気づかれる]
「あら…」

生き物の視線が、彼に向く。硬直したまま、彼は動くことができない。まるで、ヘビに睨まれたカエルのように。生き物は、ぺろりと舌舐めずりをすると、首を曲げて頭を彼に向けた。緑色の虹彩と、その中の丸い瞳孔に、彼の姿が反射する。anchor:音の正体[]その時、彼は気がついた。さっき聞こえた音が、この舌舐めずりの音なのだと。

「あなた、見ちゃった…？」

生き物の口から、はっきりとした言葉が発せられる。

「ふふ…今日はツイてる。spacing:5[]こんなに美味しそうなゴハンを見つけられるなんて…♪」
