---
description: 目の前で人を呑み込んだ竜は、通りすがりの青年をも喰らおうとする。青年は必死で逃げる。だが、竜はしぶとく追いかけてきて…
tweetable: true
layout: novel.pug
---
= #02 喰われた者を背に逃げる

[#次の獲物を見つけた捕食者]
「こんなに美味しそうなゴハンを見つけられるなんて…♪」

巨大な生き物は、ヒト一人を呑み込んだ口で舌舐めずりをしてから、はっきりと、そうつぶやいた。

[#復唱する獲物]
「ゴ…ゴハン…？」

「あら、良かった。固まっていたから、通じていないのかと思っちゃったわ」

自分に向けられたその言葉を、思わずボソリと復唱する青年。体をこわばらせる彼に、生き物は顔を近づけ、ニッコリと笑みを浮かべる。

[#人喰いの事実を受け入れがたい獲物]
「ゴハンって…今…食べて…あれ…アレは…」

彼は体をピクピクと震わせ、冷や汗をかき、しどろもどろな話し方でそう声を出す。混乱と恐怖に包まれた彼は、絞り出したような声をだすので精一杯。

[#前の犠牲者を語る捕食者]
「フフ…もしかして、今私が食べたゴハンの事を言ってるの？」

そんな彼の目の前で、生き物はゆっくりと口を開け、優しげな声色で語りかける。

「二匹で楽しそうにしていたから、私が両方とも食べちゃったの」

舌と牙を彼に見せつけるように、生き物は大きな口を動かす。

[#二匹の獲物の喰らい方]
「あの箱の中にいたから、先に一匹引きずり出して──」

生き物は、前脚の爪で彼の背後を指差す。そこにあるのは、事故を起こしてひしゃげた、誰も乗っていない自動車。

「それからもう一匹も追いかけて、捕まえてあげたの」

[#犠牲者の末路]
彼は、生き物の口の中を見てしまう。白く大きな牙。テラテラと光る分厚い舌。そして、喰われた獲物が消えていった、喉の奥の暗闇。

「でもね、一匹を食べたら、もう一匹は気絶して、すぐに動かなくなっちゃったのよ。可愛く鳴いてくれるかと思ったのに…残念」

[#喰らいつく捕食者]
生き物が、頭部を彼の真上へ動かす。地面に立つ彼を、上から見下ろすような位置へ。

「あなたは気絶しないでね？お腹の中でも、しっかりと鳴いてもらうんだから…♪」

その一言を発した直後、生き物は大きく口を開け、彼に喰らいつかんばかりに頭を下げた。

[#倒れ逃れる獲物]
「うわぁぁっ！！」

一気に迫る巨大な口。見上げていた彼は、甲高い悲鳴を上げて倒れた。

ガキンッ！

地面に倒れた彼の真上で、生き物の牙がガッチリと閉じる。その距離、わずか30センチ。

「あら、避けたの？」

頭を上げた生き物は、地面に倒れた彼を見て言う。

[#必死で逃げる獲物]
「まずい…マズイ…っ！」

彼は必死の形相で立ち上がると、何度も倒れそうになりながら、フラフラと走り出した。

「フフフ…どこへ行くつもり？」

背後から、生き物の声が聞こえる。anchor:自転車に飛び乗る獲物[]彼はそれを振り返ることもなく走り、壁に立てかけていた自転車へすがりついた。

（逃げないと…逃げないと…逃げなきゃ…逃げなきゃ…！）

まるで念仏のように、心の中で何度も繰り返しながら、彼は自転車に飛び乗り、力任せにruby:漕[こ]ぎだした。

[#視界に映る自宅]
彼の視界に、自分の家の姿がうつる。畑と林に囲まれた、およそ9軒の家々。その中の、見慣れた一軒家。家と家の間に続く、短い道路へのT字路。そこを曲がれば、もう目と鼻の先だ。自転車を旋回させ、曲がろうとした、その時。

「ギャアッ！！」

[#唐突な足の激痛]
力任せにこいでいた左足に、強い激痛が走った。口からは悲鳴が漏れ、自転車ごと道に倒れてしまう。

「ハァ…ハァ…ッ！」

左足がズキズキと痛む。家の入口まであと5メートル。anchor:玄関までたどり着く[]彼は自転車を押しのけると、びっこを引いて歩きだした。

（ruby:攣[つ]ったのか何なのか知らないけど…こんな足で自転車をruby:漕[こ]ぐくらいなら、歩いたほうがずっとマシだ…！）

青い顔をした彼は、体を震わせながらノロノロと歩き、なんとか玄関までたどりつく。anchor:首を這う捕食者の吐息[]とうとう自宅についたという安心感からか、彼はドアノブを掴んだままへたり込んでしまった。

「そこがあなたのruby:棲家[すみか]なの？」

そんな彼のすぐ後ろ、20センチほどの至近距離から、優しげな声色が聞こえた。彼の首筋を、生暖かい吐息が撫でる。

[#帰宅]
「ギャアアッ！」

後ろを振り返ることもせずに、彼は玄関のドアを開き、中へ滑り込むようにして入った。そして、すばやく扉を閉め、カギをかける。玄関の扉から、彼はジリジリと後退りする。その時、後ろから声がかけられた。

[#駆け寄る母]
「どうしたの！？今の音は？」

焦りが混じったその声は、彼が聞き慣れていた母親のもの。

「あ…ああ…お母さん…」

[#目に浮かぶ安堵の涙]
彼は声を震わせながら、母親の方を見る。彼は、ドアのカギから手を放し、体を反転させて母親の方を向く。

「ただいま…っ」

やっと帰ってきた。そう実感した途端、彼の目からは涙が溢れ出した。鼻に涙が入り、意図せず涙声を発してしまう。

[#怪我に驚く母]
「おかえ──どうしたのその足！？」

「…へ？」

おかえりと言いかけた母親は、大声を上げた。彼が、母親の視線の先を見ると──

[#大怪我の足]
左足が、赤く染まっていた。いや、正確には、出血でズボンが赤黒く変化していた。太ももの側面がざっくりと切れ、そこからダラダラと血が流れ出ている。血は足をつたって、玄関の土間にポタポタと滴り落ちている。anchor:足の激痛の正体[]彼の脳裏に、さっき左足に走った激痛が思い浮かんだ。筋肉痛かと思っていたあの痛みは、深さ1センチはありそうなこの怪我の痛みだった。

[#よみがえる激痛]
「あっ…ウ、ギギギ…ガ…ァッ…！」

怪我の存在を認識した途端、足がひどく痛み始める。強い痛みで、彼の額は汗ばみ、喉の奥から声にならない悲鳴が漏れ出た。anchor:なにゆえ彼は鈍痛だったのか[]逃げることに必死だった彼の体は、怪我の痛みを無視し、彼を歩かせていた。だが、怪我の存在を自覚した今、もはやそれは無視できるものではない。彼の体は、忘れていた痛みを元に戻してしまった。

「ま、待ってて！今から病院へ行こう！準備するからそこで──」

[#母を止める]
「ひっ！？だ、だめっ！」

慌てた母親は、病院へ向かおうとする。焦る母親の言葉を聞いた途端、彼は必死に止めた。いま外に出れば、アレが、あの生き物がいる。車の中のヒトも引きずり出して喰ってしまうバケモノが。

[#包帯を下さい]
「だめって…でもその怪我、すぐに病院へ行かないと！」

「いや、今は…今は駄目…それより、包帯！包帯とガーゼ持ってきて！圧迫止血するから！…ガァッ！」

「わ、分かった…持ってくるね」

彼に急かされるまま、母親は部屋の奥に入る。anchor:止血その１：脱衣[]しばらくして、母親は包帯とガーゼ、それから消毒薬を持ってきた。

「はい。ガーゼと包帯と…消毒薬。大丈夫？服は脱げる？」

母親に手伝われながら、彼は上着とズボンを脱ぎ、ゆっくりと廊下に座った。

[#止血その２：包帯巻きつけ]
「まず先に消毒を──」

「消毒はいい。傷が深いから…先に、止血を…ウッ…いたっ…」

彼は、パックリ開いた傷にガーゼを押し当てる。それから包帯を強く巻き、しっかりと縛った。

[#止血その３：血汚れ拭き取り]
「はい、タオル」

「ありがと」

母親が、彼に濡れたタオルを渡す。血で染まった靴下を脱ぎ、彼は足をタオルで拭き取った。

[#顔を出した父]
「おいおい、どうした？」

この騒動をききつけたのだろう。廊下の奥から、彼の父親が歩いてきた。

「この子、怪我して帰ってきたみたいで…」

[#詳細すぎる怪我の報告]
「怪我って…どんな怪我だ？」

「えーっと…」

彼は、怪我の様子を思い浮かべながら、慎重に答えた。

「…深さおよそ1cm、幅およそ1.0から1.2cmの…切り傷」

「そんな細かくなくていい。重症じゃないか…すぐに病院に──」

「だ、だめっ！」

[#父を止める]
母親と同じく病院へ行こうとする父親を、彼は再び止める。

「どうしてだめなの？」

「だって──」

外には怪物がいる。そう言おうとしたとき、彼は口を止めた。そう言ったところで、はたして両親は信じるだろうか。anchor:真実よりも嘘[]いつもみたく、変なことを言っているのだと言われて、病院へ行こうとするのではないだろうか。もし、無理矢理にでも連れ出されたら…

「…だって、夜中に来られたら病院が迷惑するでしょ？」

「なに言ってるの！そんな大怪我、むしろ行かなきゃ駄目でしょ！？」

[#無価値感]
「大丈夫、ただの怪我だから…それに、もっと重症の人が他にもいるって。そういう人が行くべきなんだよ…」

「でも──」

「明日！ね？行くのは明日！明日の朝に──ウッ…？」

そこまで言いかけたとき、彼の視界がぐらりと歪んだ。anchor:めまい[]平衡感覚がおかしい。頭がぼんやりとする。彼はそのまま、廊下にバタリと倒れてしまった。

「大丈夫！？ねぇ、しっかりして！」

母親の声が聞こえる。だが、頭がクラクラして、なんだか聞こえ方がおかしい。

[#遺す言葉]
「出ないで…」

意識が朦朧とする中、彼は何度も呟いた。

「出ないで…家から出ないで…出ちゃだめ…出ちゃ…」

何度も何度も、うわ言のように呟きながら、彼は意識を失ってしまった。
